### ISSUE TITLE
Update info.json and repository.json

### ISSUE THREAD

**Issue by PhilPJL** [SolastaMods/SolastaModTemplate#2]
Create git release 0.0.1 of SolastaModTemplate.
Update repository.json appropriately, e.g.

```
{
	"Releases": [
		{
			"Id": "SolastaMonsterHintedHealth",
			"Version": "0.0.1",
			"DownloadUrl": "https://github.com/SolastaMods/SolastaModTemplate/releases/download/V0.0.1/SolastaModTemplate.zip"
		}
	]
}

Update readme with instructions on releasing mod on github + nexus.

**Comment by ThyWoof** [comment]
Thanks. I'll update README.md later as researching how I can fully automate this workflow. Right now:

1. 3 places where we must update the version: CSPROJ, Info.json, Repository.json
2. Build "Install Release" and ZIP payload
3. Create new release on GIT ensuring we're respecting nomenclature (as Repository.json is built with a to-be existing link)
4. Update Nexus with new release

**Comment by PhilPJL** [comment]
Also I find there's a bit of an issue if you need
  "HomePage": "https://www.nexusmods.com/solastacrownofthemagister/mods/54",
in info.json, since you can't set the id until you've released on Nexus.
I end up releasing with /xx and then immediately re-releasing.  Must be a better way.

**Comment by ThyWoof** [comment]
@PhilPJL , here is the workflow I've been using:

1. Create a new repo on GitHub on Browser UI
2. Run CREATE_SOLASTA_MOD.PS1 on my computer to get template and first commit to Repo
3. Develop / Test the Mod
4. Create new hidden Mod on Nexus page with minimum required entries. Get Nexus URL
5. Edit version entries on CSPROJ, Info.json, and Repository.json (I always start with 0.0.1)
6. Edit Info.json and fix Nexus URL
7. Release Mod on GitHub using Vx.y.z as TAG/RELEASE convention (I always start with V0.0.1)
8. Update Nexus page with download file

**Comment by ThyWoof** [comment]
@PhilPJL , update both README.md and README-TEMPLATE.md. Please let me know if any better so I can close this.

**Comment by PhilPJL** [comment]
Looks good.
